spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  jackson:
    time-zone: Asia/Seoul
  mvc:
    format:
      date-time: "yyyy-MM-dd'T'HH:mm:ss"
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  servers:
    - url: https://api.meet.chuseok22.com
      description: main-server
    - url: http://chuseok22.synology.me:8092
      description: test-server
    - url: http://localhost:8080
      description: local-server

  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /docs/swagger
server:
  forward-headers-strategy: framework

chuseok22:
  api-change-log:
    enabled: true               # 기능 활성화 (기본값: true)
    entries-to-show: 10         # 표시할 최대 변경 이력 개수 (기본값: 10)
    date-format: "yyyy-MM-dd"   # 날짜 표시 형식 (기본값: "yyyy-MM-dd")